version: "3.7"

services:
    api:
        build: api
        ports: [8090:8090]
        container_name: govideo-api
    web:
        build: web
        ports: [8080:8080]
        depends_on:
            - api
        container_name: govideo-web